#!/bin/sh

gdialog --title "Select" --yesno "Are you a man?" 9 18
case "$?" in
	0) gdialog --inputbox "Good day, Boy. What is your name?" 5 20 2> _1.txt
		Q_N=$(cat _1.txt)
echo "Hie, $Q_N";;
1) gedialog --infobox "Good day, Girl" 5, 20;;
*) gdialog --infobox "Good day" 5, 20;;
esac
sleep 1
exit 0
